Add check of diff action.yaml & reece/action.yaml

diff --git a/.github/workflows/test-and-release.yml b/.github/workflows/test-and-release.yml
--- a/.github/workflows/test-and-release.yml
+++ b/.github/workflows/test-and-release.yml
@@ -43,6 +43,25 @@ jobs:
         with:
           strict: true
 
+  reece-diff:
+    runs-on: ubuntu-latest
+    steps:
+      - id: checkout
+        name: Checkout code 🛒
+        uses: actions/checkout@v3
+
+      - id: diff
+        name: Check that reece/action.yaml only differs where it should 🔎
+        shell: bash
+        run: |
+          set +euo pipefail
+          lines="$(diff -u0 action.yaml reece/action.yaml | grep -Ev "image: ('Dockerfile|docker://)" | wc -l)"
+          set -euo pipefail
+          if [[ "${lines}" != "3" ]] ; then
+            echo "ERROR: action.yaml and reece/action.yaml should only differ on the image: line"
+            exit 1
+          fi
+
   update-doc:
     if: ${{ github.ref_name != github.event.repository.default_branch }}
     runs-on: ubuntu-latest
@@ -79,10 +98,12 @@ jobs:
   release:
     needs:
       - pylint
+      - reece-diff
       - yamllint
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - id: checkout
+        name: Checkout code 🛒
         uses: actions/checkout@v3
 
       - name: Get next version
